name: PR Verify

on:
  pull_request:
    branches: 
      - master
      - main

env:
  DOTNET_VERSION: 9.x
  BUILD_CONFIG: Release

jobs:
  build:
    name: PR Verify
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: .NET Restore
        run: dotnet restore --locked-mode

      - name: .NET Build
        run: dotnet build --configuration $BUILD_CONFIG --no-restore

      - name: .NET Test
        run: dotnet test --configuration $BUILD_CONFIG --no-build
