name: PR Verify

on:
  pull_request:
    branches: 
      - master
      - main

jobs:
  build:
    name: PR Verify
    runs-on: ubuntu-latest
    env:
      BUILD_CONFIG: Release

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0   

      - name: Set up .NET
        uses: actions/setup-dotnet@v5
        env:
          DOTNET_VERSION: 9.x
        with:
          global-json-file: global.json
          dotnet-version: $DOTNET_VERSION
          cache: true

      - name: .NET Restore
        run: dotnet restore --locked-mode

      - name: .NET Build
        run: dotnet build --configuration $BUILD_CONFIG --no-restore

      - name: .NET Test
        run: dotnet test --configuration $BUILD_CONFIG --no-build
